// Top-10 categories. Each item has aliases to handle variant spellings.
// Order in `items` IS the ranking (index 0 = #1).
window.CATEGORIES = [
  {
    id: "populous-countries",
    category: "Geography",
    prompt: "Most populous countries in the world",
    hint: "2024 population estimates",
    items: [
      { name: "India",         aliases: ["Bharat", "Republic of India"] },
      { name: "China",         aliases: ["PRC", "People's Republic of China", "Chine"] },
      { name: "United States", aliases: ["USA", "US", "America", "United States of America", "Etats-Unis", "U.S.A.", "U.S."] },
      { name: "Indonesia",     aliases: ["Indonesie"] },
      { name: "Pakistan",      aliases: [] },
      { name: "Nigeria",       aliases: [] },
      { name: "Brazil",        aliases: ["Bresil", "Brasil"] },
      { name: "Bangladesh",    aliases: [] },
      { name: "Russia",        aliases: ["Russian Federation", "Russie"] },
      { name: "Mexico",        aliases: ["Mexique", "Mejico"] },
    ],
  },
  {
    id: "largest-countries",
    category: "Geography",
    prompt: "Largest countries by area",
    hint: "Total land + water area",
    items: [
      { name: "Russia",        aliases: ["Russian Federation", "Russie"] },
      { name: "Canada",        aliases: [] },
      { name: "United States", aliases: ["USA", "US", "America", "United States of America", "Etats-Unis"] },
      { name: "China",         aliases: ["PRC", "People's Republic of China", "Chine"] },
      { name: "Brazil",        aliases: ["Bresil", "Brasil"] },
      { name: "Australia",     aliases: ["Australie"] },
      { name: "India",         aliases: ["Bharat"] },
      { name: "Argentina",     aliases: ["Argentine"] },
      { name: "Kazakhstan",    aliases: [] },
      { name: "Algeria",       aliases: ["Algerie"] },
    ],
  },
  {
    id: "smallest-countries",
    category: "Geography",
    prompt: "Smallest countries by area",
    hint: "Sovereign states only",
    items: [
      { name: "Vatican City",     aliases: ["Holy See", "Vatican"] },
      { name: "Monaco",           aliases: [] },
      { name: "Nauru",            aliases: [] },
      { name: "Tuvalu",           aliases: [] },
      { name: "San Marino",       aliases: [] },
      { name: "Liechtenstein",    aliases: [] },
      { name: "Marshall Islands", aliases: [] },
      { name: "Saint Kitts and Nevis", aliases: ["St Kitts and Nevis", "St. Kitts and Nevis"] },
      { name: "Maldives",         aliases: [] },
      { name: "Malta",            aliases: [] },
    ],
  },
  {
    id: "highest-mountains",
    category: "Geography",
    prompt: "Highest mountains in the world",
    hint: "Independent peaks above 8,000m",
    items: [
      { name: "Mount Everest",  aliases: ["Everest", "Sagarmatha", "Chomolungma"] },
      { name: "K2",             aliases: ["Mount Godwin-Austen", "Chhogori"] },
      { name: "Kangchenjunga",  aliases: ["Kanchenjunga"] },
      { name: "Lhotse",         aliases: [] },
      { name: "Makalu",         aliases: [] },
      { name: "Cho Oyu",        aliases: [] },
      { name: "Dhaulagiri",     aliases: ["Dhaulagiri I"] },
      { name: "Manaslu",        aliases: [] },
      { name: "Nanga Parbat",   aliases: [] },
      { name: "Annapurna",      aliases: ["Annapurna I"] },
    ],
  },
  {
    id: "longest-rivers",
    category: "Geography",
    prompt: "Longest rivers in the world",
    hint: "By length, including main tributary systems",
    items: [
      { name: "Nile",          aliases: ["River Nile", "Nil"] },
      { name: "Amazon",        aliases: ["Amazonas", "Amazone"] },
      { name: "Yangtze",       aliases: ["Chang Jiang"] },
      { name: "Mississippi",   aliases: ["Mississippi-Missouri"] },
      { name: "Yenisei",       aliases: ["Yenisey"] },
      { name: "Yellow River",  aliases: ["Huang He", "Huanghe"] },
      { name: "Ob",            aliases: ["Ob-Irtysh", "Obi"] },
      { name: "Parana",        aliases: ["Paraná"] },
      { name: "Congo",         aliases: ["Zaire River"] },
      { name: "Amur",          aliases: ["Heilong Jiang", "Heilongjiang"] },
    ],
  },
  {
    id: "largest-islands",
    category: "Geography",
    prompt: "Largest islands in the world",
    hint: "By area (Australia excluded — it's a continent)",
    items: [
      { name: "Greenland",        aliases: ["Kalaallit Nunaat", "Groenland"] },
      { name: "New Guinea",       aliases: ["Papua"] },
      { name: "Borneo",           aliases: ["Kalimantan"] },
      { name: "Madagascar",       aliases: [] },
      { name: "Baffin Island",    aliases: ["Baffin"] },
      { name: "Sumatra",          aliases: ["Sumatera"] },
      { name: "Honshu",           aliases: ["Honshū"] },
      { name: "Victoria Island",  aliases: ["Victoria"] },
      { name: "Great Britain",    aliases: ["Britain"] },
      { name: "Ellesmere Island", aliases: ["Ellesmere"] },
    ],
  },
  {
    id: "most-visited-countries",
    category: "Travel",
    prompt: "Most visited countries by tourists",
    hint: "International tourist arrivals (pre-2020 standard)",
    items: [
      { name: "France",          aliases: [] },
      { name: "Spain",           aliases: ["Espana"] },
      { name: "United States",   aliases: ["USA", "US", "America"] },
      { name: "China",           aliases: ["PRC"] },
      { name: "Italy",           aliases: ["Italia"] },
      { name: "Turkey",          aliases: ["Türkiye", "Turkiye"] },
      { name: "Mexico",          aliases: [] },
      { name: "Germany",         aliases: ["Deutschland"] },
      { name: "Thailand",        aliases: [] },
      { name: "United Kingdom",  aliases: ["UK", "Britain", "Great Britain"] },
    ],
  },
  {
    id: "populous-european-countries",
    category: "Geography",
    prompt: "Most populous countries in Europe",
    hint: "Includes Russia (European population)",
    items: [
      { name: "Russia",         aliases: ["Russian Federation"] },
      { name: "Germany",        aliases: ["Deutschland"] },
      { name: "United Kingdom", aliases: ["UK", "Britain", "Great Britain"] },
      { name: "France",         aliases: [] },
      { name: "Italy",          aliases: ["Italia"] },
      { name: "Spain",          aliases: ["Espana"] },
      { name: "Poland",         aliases: ["Polska"] },
      { name: "Ukraine",        aliases: [] },
      { name: "Romania",        aliases: ["Romanya"] },
      { name: "Netherlands",    aliases: ["Holland"] },
    ],
  },
  {
    id: "populous-us-states",
    category: "USA",
    prompt: "Most populous U.S. states",
    items: [
      { name: "California",     aliases: ["CA", "Cali"] },
      { name: "Texas",          aliases: ["TX"] },
      { name: "Florida",        aliases: ["FL"] },
      { name: "New York",       aliases: ["NY", "New York State"] },
      { name: "Pennsylvania",   aliases: ["PA"] },
      { name: "Illinois",       aliases: ["IL"] },
      { name: "Ohio",           aliases: ["OH"] },
      { name: "Georgia",        aliases: ["GA"] },
      { name: "North Carolina", aliases: ["NC"] },
      { name: "Michigan",       aliases: ["MI"] },
    ],
  },
  {
    id: "largest-us-states",
    category: "USA",
    prompt: "Largest U.S. states by area",
    items: [
      { name: "Alaska",     aliases: ["AK"] },
      { name: "Texas",      aliases: ["TX"] },
      { name: "California", aliases: ["CA"] },
      { name: "Montana",    aliases: ["MT"] },
      { name: "New Mexico", aliases: ["NM"] },
      { name: "Arizona",    aliases: ["AZ"] },
      { name: "Nevada",     aliases: ["NV"] },
      { name: "Colorado",   aliases: ["CO"] },
      { name: "Oregon",     aliases: ["OR"] },
      { name: "Wyoming",    aliases: ["WY"] },
    ],
  },
  {
    id: "most-spoken-languages",
    category: "Languages",
    prompt: "Most spoken languages in the world",
    hint: "Total speakers (native + second language)",
    items: [
      { name: "English",       aliases: ["Anglais"] },
      { name: "Mandarin",      aliases: ["Mandarin Chinese", "Chinese", "Putonghua"] },
      { name: "Hindi",         aliases: [] },
      { name: "Spanish",       aliases: ["Espanol", "Castellano"] },
      { name: "French",        aliases: ["Francais"] },
      { name: "Arabic",        aliases: ["Arabe"] },
      { name: "Bengali",       aliases: ["Bangla"] },
      { name: "Portuguese",    aliases: ["Portugues"] },
      { name: "Russian",       aliases: ["Russe"] },
      { name: "Urdu",          aliases: [] },
    ],
  },
  {
    id: "largest-deserts",
    category: "Geography",
    prompt: "Largest deserts in the world",
    hint: "By area — includes polar deserts",
    items: [
      { name: "Antarctic Desert",      aliases: ["Antarctica"] },
      { name: "Arctic Desert",         aliases: ["Arctic"] },
      { name: "Sahara",                aliases: ["Sahara Desert"] },
      { name: "Arabian Desert",        aliases: ["Arabia"] },
      { name: "Gobi",                  aliases: ["Gobi Desert"] },
      { name: "Kalahari",              aliases: ["Kalahari Desert"] },
      { name: "Patagonian Desert",     aliases: ["Patagonia"] },
      { name: "Great Victoria Desert", aliases: ["Victoria Desert"] },
      { name: "Syrian Desert",         aliases: [] },
      { name: "Great Basin Desert",    aliases: ["Great Basin"] },
    ],
  },
  {
    id: "largest-lakes",
    category: "Geography",
    prompt: "Largest lakes in the world",
    hint: "By surface area — Caspian counts as a lake",
    items: [
      { name: "Caspian Sea",    aliases: ["Caspian"] },
      { name: "Superior",       aliases: ["Lake Superior"] },
      { name: "Victoria",       aliases: ["Lake Victoria"] },
      { name: "Huron",          aliases: ["Lake Huron"] },
      { name: "Michigan",       aliases: ["Lake Michigan"] },
      { name: "Tanganyika",     aliases: ["Lake Tanganyika"] },
      { name: "Baikal",         aliases: ["Lake Baikal"] },
      { name: "Great Bear Lake", aliases: ["Great Bear"] },
      { name: "Malawi",         aliases: ["Lake Malawi", "Lake Nyasa"] },
      { name: "Great Slave Lake", aliases: ["Great Slave"] },
    ],
  },
  {
    id: "tallest-buildings",
    category: "Architecture",
    prompt: "Tallest buildings in the world",
    hint: "By height to architectural top",
    items: [
      { name: "Burj Khalifa",          aliases: ["Burj Dubai"] },
      { name: "Merdeka 118",           aliases: ["Merdeka"] },
      { name: "Shanghai Tower",        aliases: [] },
      { name: "Abraj Al-Bait Clock Tower", aliases: ["Makkah Royal Clock Tower", "Mecca Clock Tower", "Abraj Al Bait"] },
      { name: "Ping An Finance Center", aliases: ["Ping An"] },
      { name: "Lotte World Tower",     aliases: ["Lotte World"] },
      { name: "One World Trade Center", aliases: ["1 WTC", "Freedom Tower", "One WTC"] },
      { name: "Guangzhou CTF Finance Centre", aliases: ["CTF Guangzhou"] },
      { name: "Tianjin CTF Finance Centre", aliases: ["CTF Tianjin"] },
      { name: "China Zun",             aliases: ["CITIC Tower"] },
    ],
  },
  {
    id: "highest-grossing-films",
    category: "Movies",
    prompt: "Highest-grossing films worldwide",
    hint: "Unadjusted box office",
    items: [
      { name: "Avatar",                          aliases: [] },
      { name: "Avengers: Endgame",               aliases: ["Endgame", "Avengers Endgame"] },
      { name: "Avatar: The Way of Water",        aliases: ["Avatar 2", "The Way of Water"] },
      { name: "Titanic",                         aliases: [] },
      { name: "Star Wars: The Force Awakens",    aliases: ["The Force Awakens", "Star Wars 7"] },
      { name: "Avengers: Infinity War",          aliases: ["Infinity War"] },
      { name: "Spider-Man: No Way Home",         aliases: ["No Way Home", "Spiderman No Way Home"] },
      { name: "Inside Out 2",                    aliases: [] },
      { name: "Jurassic World",                  aliases: [] },
      { name: "The Lion King",                   aliases: ["Lion King 2019", "Lion King"] },
    ],
  },
  {
    id: "highest-grossing-animated",
    category: "Movies",
    prompt: "Highest-grossing animated films",
    items: [
      { name: "Inside Out 2",                aliases: [] },
      { name: "Frozen 2",                    aliases: ["Frozen II"] },
      { name: "Frozen",                      aliases: [] },
      { name: "The Super Mario Bros. Movie", aliases: ["Super Mario Bros Movie", "Mario Movie"] },
      { name: "Incredibles 2",               aliases: ["The Incredibles 2"] },
      { name: "Minions",                     aliases: [] },
      { name: "The Lion King",               aliases: ["Lion King 2019"] },
      { name: "Toy Story 4",                 aliases: [] },
      { name: "Toy Story 3",                 aliases: [] },
      { name: "Despicable Me 3",             aliases: [] },
    ],
  },
  {
    id: "highest-grossing-franchises",
    category: "Movies",
    prompt: "Highest-grossing film franchises",
    hint: "Total worldwide box office across all films",
    items: [
      { name: "Marvel Cinematic Universe", aliases: ["MCU", "Marvel"] },
      { name: "Star Wars",                 aliases: [] },
      { name: "Harry Potter",              aliases: ["Wizarding World"] },
      { name: "James Bond",                aliases: ["007", "Bond"] },
      { name: "Spider-Man",                aliases: ["Spiderman"] },
      { name: "Avengers",                  aliases: [] },
      { name: "The Lord of the Rings",     aliases: ["Lord of the Rings", "LOTR"] },
      { name: "Batman",                    aliases: [] },
      { name: "Fast and Furious",          aliases: ["The Fast and the Furious", "Fast & Furious"] },
      { name: "X-Men",                     aliases: ["Xmen"] },
    ],
  },
  {
    id: "best-selling-artists",
    category: "Music",
    prompt: "Best-selling music artists of all time",
    hint: "Certified total record sales worldwide",
    items: [
      { name: "The Beatles",     aliases: ["Beatles"] },
      { name: "Elvis Presley",   aliases: ["Elvis"] },
      { name: "Michael Jackson", aliases: ["MJ"] },
      { name: "Madonna",         aliases: [] },
      { name: "Elton John",      aliases: [] },
      { name: "Led Zeppelin",    aliases: ["Zeppelin"] },
      { name: "Rihanna",         aliases: [] },
      { name: "Pink Floyd",      aliases: [] },
      { name: "Eminem",          aliases: [] },
      { name: "Mariah Carey",    aliases: [] },
    ],
  },
  {
    id: "best-selling-albums",
    category: "Music",
    prompt: "Best-selling albums of all time",
    items: [
      { name: "Thriller",                aliases: ["Michael Jackson Thriller"] },
      { name: "Back in Black",           aliases: ["AC/DC Back in Black"] },
      { name: "The Dark Side of the Moon", aliases: ["Dark Side of the Moon", "Pink Floyd Dark Side"] },
      { name: "The Bodyguard",           aliases: ["Bodyguard"] },
      { name: "Bat Out of Hell",         aliases: [] },
      { name: "Their Greatest Hits 1971-1975", aliases: ["Eagles Greatest Hits", "Eagles Greatest Hits 1971-1975"] },
      { name: "Hotel California",        aliases: [] },
      { name: "Come On Over",            aliases: ["Shania Twain Come On Over"] },
      { name: "Rumours",                 aliases: ["Fleetwood Mac Rumours"] },
      { name: "Saturday Night Fever",    aliases: [] },
    ],
  },
  {
    id: "most-viewed-youtube",
    category: "Internet",
    prompt: "Most viewed YouTube videos",
    hint: "All time, music videos dominate",
    items: [
      { name: "Baby Shark Dance",          aliases: ["Baby Shark"] },
      { name: "Despacito",                 aliases: [] },
      { name: "Johny Johny Yes Papa",      aliases: ["Johnny Johnny Yes Papa", "Johny Johny"] },
      { name: "Shape of You",              aliases: ["Ed Sheeran Shape of You"] },
      { name: "See You Again",             aliases: [] },
      { name: "Phonics Song with Two Words", aliases: ["Phonics Song"] },
      { name: "Bath Song",                 aliases: [] },
      { name: "Wheels on the Bus",         aliases: ["The Wheels on the Bus"] },
      { name: "Gangnam Style",             aliases: [] },
      { name: "Bad Romance",               aliases: ["Lady Gaga Bad Romance"] },
    ],
  },
  {
    id: "most-subscribed-youtube",
    category: "Internet",
    prompt: "Most subscribed YouTube channels",
    items: [
      { name: "MrBeast",        aliases: ["Mr Beast"] },
      { name: "T-Series",       aliases: ["TSeries", "T Series"] },
      { name: "Cocomelon",      aliases: ["Cocomelon - Nursery Rhymes"] },
      { name: "SET India",      aliases: ["Sony Entertainment Television India"] },
      { name: "Kids Diana Show", aliases: ["Diana Show"] },
      { name: "Vlad and Niki",  aliases: ["Vlad & Niki"] },
      { name: "Like Nastya",    aliases: ["Nastya"] },
      { name: "PewDiePie",      aliases: ["Pewdiepie"] },
      { name: "WWE",            aliases: [] },
      { name: "Zee Music Company", aliases: ["Zee Music"] },
    ],
  },
  {
    id: "most-followed-instagram",
    category: "Internet",
    prompt: "Most followed accounts on Instagram",
    items: [
      { name: "Instagram",           aliases: ["@instagram"] },
      { name: "Cristiano Ronaldo",   aliases: ["Cristiano", "CR7", "Ronaldo"] },
      { name: "Leo Messi",           aliases: ["Lionel Messi", "Messi"] },
      { name: "Selena Gomez",        aliases: [] },
      { name: "Kylie Jenner",        aliases: [] },
      { name: "Dwayne Johnson",      aliases: ["The Rock"] },
      { name: "Ariana Grande",       aliases: [] },
      { name: "Kim Kardashian",      aliases: [] },
      { name: "Beyonce",             aliases: ["Beyoncé"] },
      { name: "Khloe Kardashian",    aliases: ["Khloé Kardashian"] },
    ],
  },
  {
    id: "fastest-land-animals",
    category: "Animals",
    prompt: "Fastest land animals",
    hint: "Maximum running speed",
    items: [
      { name: "Cheetah",           aliases: [] },
      { name: "Pronghorn",         aliases: ["Pronghorn Antelope", "American Antelope"] },
      { name: "Springbok",         aliases: [] },
      { name: "Quarter Horse",     aliases: ["American Quarter Horse"] },
      { name: "Wildebeest",        aliases: ["Gnu"] },
      { name: "Lion",              aliases: [] },
      { name: "Blackbuck",         aliases: [] },
      { name: "Brown Hare",        aliases: ["European Hare", "Hare"] },
      { name: "Greyhound",         aliases: [] },
      { name: "Thomson's Gazelle", aliases: ["Thomsons Gazelle", "Thomson Gazelle"] },
    ],
  },
  {
    id: "largest-animals",
    category: "Animals",
    prompt: "Largest living animals by weight",
    items: [
      { name: "Blue Whale",           aliases: [] },
      { name: "Fin Whale",            aliases: [] },
      { name: "Bowhead Whale",        aliases: [] },
      { name: "Right Whale",          aliases: ["North Atlantic Right Whale", "Southern Right Whale"] },
      { name: "Sperm Whale",          aliases: [] },
      { name: "Humpback Whale",       aliases: [] },
      { name: "Gray Whale",           aliases: ["Grey Whale"] },
      { name: "Sei Whale",            aliases: [] },
      { name: "Whale Shark",          aliases: [] },
      { name: "African Elephant",     aliases: ["African Bush Elephant", "Elephant"] },
    ],
  },
  {
    id: "most-nba-titles",
    category: "Sports",
    prompt: "NBA teams with the most championships",
    items: [
      { name: "Boston Celtics",        aliases: ["Celtics"] },
      { name: "Los Angeles Lakers",    aliases: ["LA Lakers", "Lakers", "Minneapolis Lakers"] },
      { name: "Golden State Warriors", aliases: ["Warriors", "GSW"] },
      { name: "Chicago Bulls",         aliases: ["Bulls"] },
      { name: "San Antonio Spurs",     aliases: ["Spurs"] },
      { name: "Philadelphia 76ers",    aliases: ["76ers", "Sixers", "Philly 76ers"] },
      { name: "Detroit Pistons",       aliases: ["Pistons"] },
      { name: "Miami Heat",            aliases: ["Heat"] },
      { name: "New York Knicks",       aliases: ["Knicks"] },
      { name: "Houston Rockets",       aliases: ["Rockets"] },
    ],
  },
  {
    id: "most-super-bowls",
    category: "Sports",
    prompt: "NFL teams with the most Super Bowl wins",
    items: [
      { name: "Pittsburgh Steelers",   aliases: ["Steelers"] },
      { name: "New England Patriots",  aliases: ["Patriots", "Pats"] },
      { name: "Dallas Cowboys",        aliases: ["Cowboys"] },
      { name: "San Francisco 49ers",   aliases: ["49ers", "Niners", "SF 49ers"] },
      { name: "Green Bay Packers",     aliases: ["Packers"] },
      { name: "Kansas City Chiefs",    aliases: ["Chiefs", "KC Chiefs"] },
      { name: "New York Giants",       aliases: ["Giants", "NY Giants"] },
      { name: "Denver Broncos",        aliases: ["Broncos"] },
      { name: "Las Vegas Raiders",     aliases: ["Raiders", "Oakland Raiders", "LA Raiders"] },
      { name: "Washington Commanders", aliases: ["Commanders", "Washington Redskins", "Redskins"] },
    ],
  },
  {
    id: "mens-grand-slam-titles",
    category: "Sports",
    prompt: "Men's players with the most tennis Grand Slam singles titles",
    items: [
      { name: "Novak Djokovic",  aliases: ["Djokovic", "Nole"] },
      { name: "Rafael Nadal",    aliases: ["Nadal", "Rafa"] },
      { name: "Roger Federer",   aliases: ["Federer", "Fed"] },
      { name: "Pete Sampras",    aliases: ["Sampras"] },
      { name: "Roy Emerson",     aliases: ["Emerson"] },
      { name: "Rod Laver",       aliases: ["Laver"] },
      { name: "Bjorn Borg",      aliases: ["Björn Borg", "Borg"] },
      { name: "Bill Tilden",     aliases: ["Tilden"] },
      { name: "Andre Agassi",    aliases: ["Agassi"] },
      { name: "Jimmy Connors",   aliases: ["Connors"] },
    ],
  },
  {
    id: "womens-grand-slam-titles",
    category: "Sports",
    prompt: "Women's players with the most tennis Grand Slam singles titles",
    items: [
      { name: "Margaret Court",       aliases: ["Court"] },
      { name: "Serena Williams",      aliases: ["Serena"] },
      { name: "Steffi Graf",          aliases: ["Graf"] },
      { name: "Helen Wills",          aliases: ["Helen Wills Moody"] },
      { name: "Chris Evert",          aliases: ["Evert"] },
      { name: "Martina Navratilova",  aliases: ["Navratilova"] },
      { name: "Billie Jean King",     aliases: ["BJK", "King"] },
      { name: "Maureen Connolly",     aliases: ["Maureen Connolly Brinker", "Little Mo"] },
      { name: "Monica Seles",         aliases: ["Seles"] },
      { name: "Suzanne Lenglen",      aliases: ["Lenglen"] },
    ],
  },
  {
    id: "ballon-dor",
    category: "Sports",
    prompt: "Players with the most Ballon d'Or wins",
    items: [
      { name: "Lionel Messi",     aliases: ["Messi", "Leo Messi"] },
      { name: "Cristiano Ronaldo", aliases: ["Ronaldo", "CR7", "Cristiano"] },
      { name: "Michel Platini",   aliases: ["Platini"] },
      { name: "Johan Cruyff",     aliases: ["Cruyff"] },
      { name: "Marco van Basten", aliases: ["van Basten", "Van Basten"] },
      { name: "Franz Beckenbauer", aliases: ["Beckenbauer"] },
      { name: "Alfredo di Stefano", aliases: ["di Stefano", "Di Stefano", "Alfredo Di Stefano"] },
      { name: "Ronaldo",          aliases: ["Ronaldo Nazario", "R9", "Ronaldo Brazil", "Ronaldo Fenomeno"] },
      { name: "Karim Benzema",    aliases: ["Benzema"] },
      { name: "Luka Modric",      aliases: ["Modric"] },
    ],
  },
  {
    id: "champions-league-titles",
    category: "Sports",
    prompt: "Clubs with the most UEFA Champions League / European Cup titles",
    items: [
      { name: "Real Madrid",       aliases: ["Real"] },
      { name: "AC Milan",          aliases: ["Milan"] },
      { name: "Bayern Munich",     aliases: ["Bayern", "FC Bayern", "Bayern Munchen", "Bayern München"] },
      { name: "Liverpool",         aliases: ["LFC"] },
      { name: "Barcelona",         aliases: ["FC Barcelona", "Barca", "Barça"] },
      { name: "Ajax",              aliases: ["AFC Ajax", "Ajax Amsterdam"] },
      { name: "Manchester United", aliases: ["Man United", "Man Utd", "United", "MUFC"] },
      { name: "Inter Milan",       aliases: ["Inter", "Internazionale"] },
      { name: "Benfica",           aliases: ["SL Benfica"] },
      { name: "Nottingham Forest", aliases: ["Forest"] },
    ],
  },
  {
    id: "world-cup-wins",
    category: "Sports",
    prompt: "Countries to have won the men's FIFA World Cup",
    hint: "Only 8 countries — name them all",
    items: [
      { name: "Brazil",     aliases: ["Bresil"] },
      { name: "Germany",    aliases: ["West Germany", "Deutschland"] },
      { name: "Italy",      aliases: ["Italia"] },
      { name: "Argentina",  aliases: [] },
      { name: "France",     aliases: [] },
      { name: "Uruguay",    aliases: [] },
      { name: "England",    aliases: [] },
      { name: "Spain",      aliases: ["Espana"] },
    ],
  },
  {
    id: "intl-goalscorers-men",
    category: "Sports",
    prompt: "All-time top international goalscorers in men's football",
    items: [
      { name: "Cristiano Ronaldo", aliases: ["CR7", "Ronaldo", "Cristiano"] },
      { name: "Lionel Messi",     aliases: ["Messi", "Leo Messi"] },
      { name: "Ali Daei",         aliases: ["Daei"] },
      { name: "Sunil Chhetri",    aliases: ["Chhetri"] },
      { name: "Mokhtar Dahari",   aliases: ["Dahari"] },
      { name: "Ferenc Puskas",    aliases: ["Puskás", "Puskas"] },
      { name: "Godfrey Chitalu",  aliases: ["Chitalu"] },
      { name: "Hussain Saeed",    aliases: ["Hussein Saeed"] },
      { name: "Pele",             aliases: ["Pelé"] },
      { name: "Sandor Kocsis",    aliases: ["Sándor Kocsis", "Kocsis"] },
    ],
  },
  {
    id: "popular-dog-breeds",
    category: "Animals",
    prompt: "Most popular dog breeds in the United States",
    hint: "AKC registration rankings",
    items: [
      { name: "French Bulldog",       aliases: ["Frenchie", "French Bull Dog"] },
      { name: "Labrador Retriever",   aliases: ["Lab", "Labrador"] },
      { name: "Golden Retriever",     aliases: ["Golden"] },
      { name: "German Shepherd",      aliases: ["GSD"] },
      { name: "Poodle",               aliases: [] },
      { name: "Bulldog",              aliases: ["English Bulldog"] },
      { name: "Rottweiler",           aliases: [] },
      { name: "Beagle",               aliases: [] },
      { name: "Dachshund",            aliases: ["Wiener Dog", "Sausage Dog"] },
      { name: "German Shorthaired Pointer", aliases: ["GSP"] },
    ],
  },
  {
    id: "best-selling-video-games",
    category: "Games",
    prompt: "Best-selling video games of all time",
    hint: "Across all platforms",
    items: [
      { name: "Minecraft",              aliases: [] },
      { name: "Grand Theft Auto V",     aliases: ["GTA V", "GTA 5"] },
      { name: "Tetris",                 aliases: ["Tetris EA"] },
      { name: "Wii Sports",             aliases: [] },
      { name: "PUBG",                   aliases: ["PlayerUnknown's Battlegrounds", "PUBG: Battlegrounds"] },
      { name: "Mario Kart 8",           aliases: ["Mario Kart 8 Deluxe", "MK8"] },
      { name: "Red Dead Redemption 2",  aliases: ["RDR2", "RDR 2"] },
      { name: "Super Mario Bros.",      aliases: ["Super Mario Bros"] },
      { name: "Pokemon Red/Blue/Green/Yellow", aliases: ["Pokemon Red", "Pokemon Blue", "Pokemon Yellow", "Pokemon Red Blue"] },
      { name: "Terraria",               aliases: [] },
    ],
  },
  {
    id: "largest-planets",
    category: "Science",
    prompt: "Largest planets in our solar system",
    hint: "By diameter",
    items: [
      { name: "Jupiter", aliases: [] },
      { name: "Saturn",  aliases: [] },
      { name: "Uranus",  aliases: [] },
      { name: "Neptune", aliases: [] },
      { name: "Earth",   aliases: [] },
      { name: "Venus",   aliases: [] },
      { name: "Mars",    aliases: [] },
      { name: "Mercury", aliases: [] },
    ],
  },
  {
    id: "most-populous-cities",
    category: "Geography",
    prompt: "Most populous metropolitan areas in the world",
    hint: "Urban agglomeration population",
    items: [
      { name: "Tokyo",       aliases: ["Greater Tokyo"] },
      { name: "Delhi",       aliases: ["New Delhi", "Delhi NCR"] },
      { name: "Shanghai",    aliases: [] },
      { name: "Dhaka",       aliases: ["Dacca"] },
      { name: "Sao Paulo",   aliases: ["São Paulo"] },
      { name: "Cairo",       aliases: ["Greater Cairo"] },
      { name: "Mexico City", aliases: ["Ciudad de Mexico", "CDMX", "Mexico DF"] },
      { name: "Beijing",     aliases: ["Peking"] },
      { name: "Mumbai",      aliases: ["Bombay"] },
      { name: "Osaka",       aliases: [] },
    ],
  },
  {
    id: "richest-people",
    category: "Business",
    prompt: "Richest people in the world",
    hint: "Approximate Forbes/Bloomberg ranking — order varies",
    items: [
      { name: "Elon Musk",         aliases: ["Musk"] },
      { name: "Jeff Bezos",        aliases: ["Bezos"] },
      { name: "Mark Zuckerberg",   aliases: ["Zuckerberg", "Zuck"] },
      { name: "Larry Ellison",     aliases: ["Ellison"] },
      { name: "Bernard Arnault",   aliases: ["Arnault"] },
      { name: "Larry Page",        aliases: ["Page"] },
      { name: "Sergey Brin",       aliases: ["Brin"] },
      { name: "Bill Gates",        aliases: ["Gates"] },
      { name: "Steve Ballmer",     aliases: ["Ballmer"] },
      { name: "Warren Buffett",    aliases: ["Buffett"] },
    ],
  },
  {
    id: "largest-companies",
    category: "Business",
    prompt: "Most valuable public companies by market cap",
    hint: "Snapshot — fluctuates daily",
    items: [
      { name: "Apple",            aliases: ["AAPL"] },
      { name: "Microsoft",        aliases: ["MSFT"] },
      { name: "Nvidia",           aliases: ["NVDA"] },
      { name: "Alphabet",         aliases: ["Google", "GOOGL", "GOOG"] },
      { name: "Amazon",           aliases: ["AMZN"] },
      { name: "Saudi Aramco",     aliases: ["Aramco"] },
      { name: "Meta",             aliases: ["Facebook", "META"] },
      { name: "Berkshire Hathaway", aliases: ["Berkshire", "BRK"] },
      { name: "TSMC",             aliases: ["Taiwan Semiconductor", "Taiwan Semiconductor Manufacturing"] },
      { name: "Tesla",            aliases: ["TSLA"] },
    ],
  },
  {
    id: "best-selling-books",
    category: "Books",
    prompt: "Best-selling book series of all time",
    items: [
      { name: "Harry Potter",          aliases: [] },
      { name: "Goosebumps",            aliases: [] },
      { name: "Perry Mason",           aliases: [] },
      { name: "Berenstain Bears",      aliases: ["The Berenstain Bears"] },
      { name: "Choose Your Own Adventure", aliases: [] },
      { name: "Diary of a Wimpy Kid",  aliases: [] },
      { name: "Robert Langdon",        aliases: ["Da Vinci Code", "Dan Brown Langdon"] },
      { name: "Nancy Drew",            aliases: [] },
      { name: "The Lord of the Rings", aliases: ["Lord of the Rings", "LOTR"] },
      { name: "Sweet Valley High",     aliases: [] },
    ],
  },
  {
    id: "oscar-best-picture-multi",
    category: "Movies",
    prompt: "Films tied with the most Academy Award wins",
    hint: "Each won 11 Oscars",
    items: [
      { name: "Ben-Hur",                        aliases: ["Ben Hur"] },
      { name: "Titanic",                        aliases: [] },
      { name: "The Lord of the Rings: The Return of the King", aliases: ["Return of the King", "LOTR Return of the King", "LOTR ROTK"] },
    ],
  },
  {
    id: "most-oscars-actors",
    category: "Movies",
    prompt: "Performers with the most acting Academy Awards",
    items: [
      { name: "Katharine Hepburn",   aliases: ["Hepburn"] },
      { name: "Daniel Day-Lewis",    aliases: ["Day-Lewis", "Daniel Day Lewis"] },
      { name: "Frances McDormand",   aliases: ["McDormand"] },
      { name: "Ingrid Bergman",      aliases: ["Bergman"] },
      { name: "Jack Nicholson",      aliases: ["Nicholson"] },
      { name: "Meryl Streep",        aliases: ["Streep"] },
      { name: "Walter Brennan",      aliases: ["Brennan"] },
      { name: "Marlon Brando",       aliases: ["Brando"] },
      { name: "Gary Cooper",         aliases: [] },
      { name: "Bette Davis",         aliases: [] },
    ],
  },
  {
    id: "f1-championships",
    category: "Sports",
    prompt: "Drivers with the most F1 World Championships",
    items: [
      { name: "Michael Schumacher", aliases: ["Schumacher"] },
      { name: "Lewis Hamilton",     aliases: ["Hamilton"] },
      { name: "Juan Manuel Fangio", aliases: ["Fangio"] },
      { name: "Max Verstappen",     aliases: ["Verstappen"] },
      { name: "Alain Prost",        aliases: ["Prost"] },
      { name: "Sebastian Vettel",   aliases: ["Vettel"] },
      { name: "Jackie Stewart",     aliases: ["Stewart"] },
      { name: "Niki Lauda",         aliases: ["Lauda"] },
      { name: "Nelson Piquet",      aliases: ["Piquet"] },
      { name: "Ayrton Senna",       aliases: ["Senna"] },
    ],
  },
  {
    id: "olympic-medals-countries",
    category: "Sports",
    prompt: "Countries with the most all-time Summer Olympic gold medals",
    items: [
      { name: "United States",  aliases: ["USA", "US", "America"] },
      { name: "Soviet Union",   aliases: ["USSR"] },
      { name: "Germany",        aliases: ["West Germany", "East Germany", "Deutschland"] },
      { name: "Great Britain",  aliases: ["United Kingdom", "UK", "Britain"] },
      { name: "France",         aliases: [] },
      { name: "Italy",          aliases: ["Italia"] },
      { name: "China",          aliases: [] },
      { name: "Hungary",        aliases: [] },
      { name: "Sweden",         aliases: [] },
      { name: "Australia",      aliases: [] },
    ],
  },
  {
    id: "expensive-paintings",
    category: "Art",
    prompt: "Most expensive paintings ever sold",
    hint: "Public auction or private sale",
    items: [
      { name: "Salvator Mundi",            aliases: [] },
      { name: "Interchange",               aliases: [] },
      { name: "The Card Players",          aliases: ["Card Players"] },
      { name: "Nafea Faa Ipoipo",          aliases: ["When Will You Marry"] },
      { name: "Number 17A",                aliases: ["No. 17A"] },
      { name: "Wasserschlangen II",        aliases: ["Water Serpents II"] },
      { name: "No. 6 (Violet, Green and Red)", aliases: ["No 6 Rothko"] },
      { name: "Pendant portraits of Maerten Soolmans and Oopjen Coppit", aliases: ["Rembrandt Pendants", "Soolmans and Coppit"] },
      { name: "Les Femmes d'Alger",        aliases: ["Women of Algiers", "Les Femmes d Alger"] },
      { name: "Nu couche",                 aliases: ["Reclining Nude", "Nu couché"] },
    ],
  },
  {
    id: "tour-de-france",
    category: "Sports",
    prompt: "Cyclists with the most Tour de France wins (recognised)",
    hint: "Lance Armstrong's wins were stripped — exclude him",
    items: [
      { name: "Jacques Anquetil",  aliases: ["Anquetil"] },
      { name: "Eddy Merckx",       aliases: ["Merckx"] },
      { name: "Bernard Hinault",   aliases: ["Hinault"] },
      { name: "Miguel Indurain",   aliases: ["Indurain"] },
      { name: "Chris Froome",      aliases: ["Froome"] },
      { name: "Tadej Pogacar",     aliases: ["Pogačar", "Pogacar"] },
      { name: "Philippe Thys",     aliases: ["Thys"] },
      { name: "Louison Bobet",     aliases: ["Bobet"] },
      { name: "Greg LeMond",       aliases: ["LeMond"] },
      { name: "Jonas Vingegaard",  aliases: ["Vingegaard"] },
    ],
  },
  {
    id: "biggest-religions",
    category: "World",
    prompt: "Largest religions by number of adherents",
    items: [
      { name: "Christianity",      aliases: ["Christian"] },
      { name: "Islam",             aliases: ["Muslim"] },
      { name: "Hinduism",          aliases: ["Hindu"] },
      { name: "Buddhism",          aliases: ["Buddhist"] },
      { name: "Folk Religions",    aliases: ["Folk Religion", "Traditional Religions", "Chinese Folk Religion"] },
      { name: "Sikhism",           aliases: ["Sikh"] },
      { name: "Judaism",           aliases: ["Jewish"] },
      { name: "Shinto",            aliases: ["Shintoism"] },
      { name: "Bahai",             aliases: ["Baha'i", "Bahai Faith", "Baháʼí"] },
      { name: "Jainism",           aliases: ["Jain"] },
    ],
  },
  {
    id: "pizza-toppings-us",
    category: "Food",
    prompt: "Most popular pizza toppings in the United States",
    items: [
      { name: "Pepperoni",       aliases: [] },
      { name: "Sausage",         aliases: ["Italian Sausage"] },
      { name: "Mushrooms",       aliases: ["Mushroom"] },
      { name: "Bacon",           aliases: [] },
      { name: "Onions",          aliases: ["Onion"] },
      { name: "Black Olives",    aliases: ["Olives"] },
      { name: "Green Peppers",   aliases: ["Bell Peppers", "Peppers"] },
      { name: "Chicken",         aliases: ["Grilled Chicken"] },
      { name: "Extra Cheese",    aliases: ["Cheese"] },
      { name: "Ham",             aliases: [] },
    ],
  },
  {
    id: "happiest-countries",
    category: "World",
    prompt: "Happiest countries (World Happiness Report)",
    items: [
      { name: "Finland",       aliases: [] },
      { name: "Denmark",       aliases: [] },
      { name: "Iceland",       aliases: [] },
      { name: "Sweden",        aliases: [] },
      { name: "Israel",        aliases: [] },
      { name: "Netherlands",   aliases: ["Holland"] },
      { name: "Norway",        aliases: [] },
      { name: "Luxembourg",    aliases: [] },
      { name: "Switzerland",   aliases: ["Suisse"] },
      { name: "Australia",     aliases: [] },
    ],
  },
  {
    id: "coffee-producers",
    category: "Food",
    prompt: "Largest coffee-producing countries",
    items: [
      { name: "Brazil",      aliases: ["Bresil", "Brasil"] },
      { name: "Vietnam",     aliases: [] },
      { name: "Colombia",    aliases: ["Colombie"] },
      { name: "Indonesia",   aliases: [] },
      { name: "Ethiopia",    aliases: [] },
      { name: "Uganda",      aliases: [] },
      { name: "Honduras",    aliases: [] },
      { name: "India",       aliases: [] },
      { name: "Peru",        aliases: [] },
      { name: "Mexico",      aliases: [] },
    ],
  },
  {
    id: "wine-producers",
    category: "Food",
    prompt: "Largest wine-producing countries",
    items: [
      { name: "Italy",          aliases: ["Italia"] },
      { name: "France",         aliases: [] },
      { name: "Spain",          aliases: ["Espana"] },
      { name: "United States",  aliases: ["USA", "US", "America"] },
      { name: "Australia",      aliases: [] },
      { name: "Chile",          aliases: [] },
      { name: "Argentina",      aliases: [] },
      { name: "South Africa",   aliases: [] },
      { name: "Germany",        aliases: ["Deutschland"] },
      { name: "Portugal",       aliases: [] },
    ],
  },
  {
    id: "biggest-economies",
    category: "Business",
    prompt: "Largest economies in the world by nominal GDP",
    items: [
      { name: "United States",  aliases: ["USA", "US", "America"] },
      { name: "China",          aliases: [] },
      { name: "Germany",        aliases: ["Deutschland"] },
      { name: "Japan",          aliases: [] },
      { name: "India",          aliases: [] },
      { name: "United Kingdom", aliases: ["UK", "Britain", "Great Britain"] },
      { name: "France",         aliases: [] },
      { name: "Italy",          aliases: ["Italia"] },
      { name: "Brazil",         aliases: ["Bresil"] },
      { name: "Canada",         aliases: [] },
    ],
  },
  {
    id: "fastest-fish",
    category: "Animals",
    prompt: "Fastest fish in the ocean",
    items: [
      { name: "Black Marlin",       aliases: [] },
      { name: "Sailfish",           aliases: [] },
      { name: "Striped Marlin",     aliases: [] },
      { name: "Wahoo",              aliases: [] },
      { name: "Mako Shark",         aliases: ["Shortfin Mako", "Shortfin Mako Shark"] },
      { name: "Atlantic Bluefin Tuna", aliases: ["Bluefin Tuna"] },
      { name: "Blue Shark",         aliases: [] },
      { name: "Bonefish",           aliases: [] },
      { name: "Swordfish",          aliases: [] },
      { name: "Yellowfin Tuna",     aliases: [] },
    ],
  },
  {
    id: "longest-rivers-europe",
    category: "Geography",
    prompt: "Longest rivers in Europe",
    items: [
      { name: "Volga",     aliases: [] },
      { name: "Danube",    aliases: [] },
      { name: "Ural",      aliases: [] },
      { name: "Dnieper",   aliases: ["Dnepr"] },
      { name: "Don",       aliases: [] },
      { name: "Pechora",   aliases: [] },
      { name: "Kama",      aliases: [] },
      { name: "Oka",       aliases: [] },
      { name: "Belaya",    aliases: [] },
      { name: "Dniester",  aliases: ["Dnestr"] },
    ],
  },
  {
    id: "highest-peaks-europe",
    category: "Geography",
    prompt: "Highest mountains in Europe",
    hint: "Caucasus included",
    items: [
      { name: "Elbrus",         aliases: ["Mount Elbrus"] },
      { name: "Dykh-Tau",       aliases: ["Dykhtau"] },
      { name: "Shkhara",        aliases: [] },
      { name: "Koshtan-Tau",    aliases: ["Koshtantau"] },
      { name: "Pik Pushkina",   aliases: ["Pushkin Peak"] },
      { name: "Dzhangi-Tau",    aliases: ["Janga"] },
      { name: "Kazbek",         aliases: ["Mount Kazbek"] },
      { name: "Mont Blanc",     aliases: [] },
      { name: "Dufourspitze",   aliases: ["Monte Rosa"] },
      { name: "Dom",            aliases: [] },
    ],
  },
  {
    id: "us-presidents-recent",
    category: "History",
    prompt: "Last ten U.S. presidents (most recent first)",
    items: [
      { name: "Donald Trump",   aliases: ["Trump"] },
      { name: "Joe Biden",      aliases: ["Biden", "Joseph Biden"] },
      { name: "Barack Obama",   aliases: ["Obama"] },
      { name: "George W. Bush", aliases: ["Bush", "GW Bush", "George Bush Jr", "Dubya"] },
      { name: "Bill Clinton",   aliases: ["Clinton"] },
      { name: "George H.W. Bush", aliases: ["Bush Sr", "George Bush Senior", "George H W Bush", "HW Bush"] },
      { name: "Ronald Reagan",  aliases: ["Reagan"] },
      { name: "Jimmy Carter",   aliases: ["Carter"] },
      { name: "Gerald Ford",    aliases: ["Ford"] },
      { name: "Richard Nixon",  aliases: ["Nixon"] },
    ],
  },
  {
    id: "longest-bridges",
    category: "Architecture",
    prompt: "Longest bridges in the world (any type)",
    items: [
      { name: "Danyang-Kunshan Grand Bridge",  aliases: ["Danyang Kunshan"] },
      { name: "Changhua-Kaohsiung Viaduct",    aliases: ["Changhua Kaohsiung"] },
      { name: "Cangde Grand Bridge",           aliases: ["Cangde Bridge"] },
      { name: "Tianjin Grand Bridge",          aliases: ["Tianjin Bridge"] },
      { name: "Weinan Weihe Grand Bridge",     aliases: ["Weinan Weihe Bridge"] },
      { name: "Bang Na Expressway",            aliases: ["Bang Na"] },
      { name: "Beijing Grand Bridge",          aliases: [] },
      { name: "Lake Pontchartrain Causeway",   aliases: ["Pontchartrain Causeway"] },
      { name: "Manchac Swamp Bridge",          aliases: ["Manchac Bridge"] },
      { name: "Yangcun Bridge",                aliases: [] },
    ],
  },
  {
    id: "english-monarchs-recent",
    category: "History",
    prompt: "Last ten monarchs of the United Kingdom / Britain (most recent first)",
    items: [
      { name: "Charles III",   aliases: ["King Charles III", "Charles 3"] },
      { name: "Elizabeth II",  aliases: ["Queen Elizabeth II", "Elizabeth 2", "QEII"] },
      { name: "George VI",     aliases: ["George 6"] },
      { name: "Edward VIII",   aliases: ["Edward 8"] },
      { name: "George V",      aliases: ["George 5"] },
      { name: "Edward VII",    aliases: ["Edward 7"] },
      { name: "Victoria",      aliases: ["Queen Victoria"] },
      { name: "William IV",    aliases: ["William 4"] },
      { name: "George IV",     aliases: ["George 4"] },
      { name: "George III",    aliases: ["George 3"] },
    ],
  },
  {
    id: "biggest-cities-france",
    category: "France",
    prompt: "Most populous cities in France (commune proper)",
    items: [
      { name: "Paris",        aliases: [] },
      { name: "Marseille",    aliases: [] },
      { name: "Lyon",         aliases: [] },
      { name: "Toulouse",     aliases: [] },
      { name: "Nice",         aliases: [] },
      { name: "Nantes",       aliases: [] },
      { name: "Montpellier",  aliases: [] },
      { name: "Strasbourg",   aliases: [] },
      { name: "Bordeaux",     aliases: [] },
      { name: "Lille",        aliases: [] },
    ],
  },
  {
    id: "best-selling-cars",
    category: "Cars",
    prompt: "Best-selling cars of all time (single nameplate)",
    items: [
      { name: "Toyota Corolla",         aliases: ["Corolla"] },
      { name: "Ford F-Series",          aliases: ["F-Series", "Ford F150", "Ford F-150"] },
      { name: "Volkswagen Golf",        aliases: ["VW Golf", "Golf"] },
      { name: "Volkswagen Beetle",      aliases: ["VW Beetle", "Beetle"] },
      { name: "Ford Escort",            aliases: ["Escort"] },
      { name: "Honda Civic",            aliases: ["Civic"] },
      { name: "Honda Accord",           aliases: ["Accord"] },
      { name: "Chevrolet Impala",       aliases: ["Impala"] },
      { name: "Lada Riva",              aliases: ["Lada 2105", "Lada Classic"] },
      { name: "Nissan Sunny",           aliases: ["Sunny"] },
    ],
  },
  {
    id: "highest-rated-imdb",
    category: "Movies",
    prompt: "Highest-rated films on IMDb (Top 250)",
    items: [
      { name: "The Shawshank Redemption",    aliases: ["Shawshank Redemption", "Shawshank"] },
      { name: "The Godfather",               aliases: ["Godfather"] },
      { name: "The Dark Knight",             aliases: ["Dark Knight"] },
      { name: "The Godfather Part II",       aliases: ["Godfather Part II", "Godfather 2", "Godfather II"] },
      { name: "12 Angry Men",                aliases: ["Twelve Angry Men"] },
      { name: "Schindler's List",            aliases: ["Schindlers List"] },
      { name: "The Lord of the Rings: The Return of the King", aliases: ["Return of the King", "LOTR Return of the King", "LOTR ROTK"] },
      { name: "Pulp Fiction",                aliases: [] },
      { name: "The Lord of the Rings: The Fellowship of the Ring", aliases: ["Fellowship of the Ring", "LOTR Fellowship"] },
      { name: "The Good, the Bad and the Ugly", aliases: ["Good Bad Ugly", "Good the Bad and the Ugly"] },
    ],
  },
  {
    id: "marvel-movies",
    category: "Movies",
    prompt: "Highest-grossing Marvel Cinematic Universe films",
    items: [
      { name: "Avengers: Endgame",         aliases: ["Endgame"] },
      { name: "Avengers: Infinity War",    aliases: ["Infinity War"] },
      { name: "Spider-Man: No Way Home",   aliases: ["No Way Home"] },
      { name: "The Avengers",              aliases: ["Avengers", "Avengers Assemble"] },
      { name: "Avengers: Age of Ultron",   aliases: ["Age of Ultron"] },
      { name: "Black Panther",             aliases: [] },
      { name: "Captain America: Civil War", aliases: ["Civil War"] },
      { name: "Iron Man 3",                aliases: [] },
      { name: "Deadpool & Wolverine",      aliases: ["Deadpool 3", "Deadpool and Wolverine"] },
      { name: "Captain Marvel",            aliases: [] },
    ],
  },
  {
    id: "oldest-universities",
    category: "History",
    prompt: "Oldest universities in continuous operation",
    items: [
      { name: "University of Bologna",        aliases: ["Bologna"] },
      { name: "University of Oxford",         aliases: ["Oxford"] },
      { name: "University of Salamanca",      aliases: ["Salamanca"] },
      { name: "University of Paris",          aliases: ["Paris University", "Sorbonne"] },
      { name: "University of Cambridge",      aliases: ["Cambridge"] },
      { name: "University of Padua",          aliases: ["Padua"] },
      { name: "University of Naples Federico II", aliases: ["Naples Federico II"] },
      { name: "University of Siena",          aliases: ["Siena"] },
      { name: "University of Coimbra",        aliases: ["Coimbra"] },
      { name: "University of Macerata",       aliases: ["Macerata"] },
    ],
  },
  {
    id: "popular-sports",
    category: "Sports",
    prompt: "Most popular sports by global following",
    hint: "Estimated fans worldwide",
    items: [
      { name: "Football",        aliases: ["Soccer", "Association Football"] },
      { name: "Cricket",         aliases: [] },
      { name: "Field Hockey",    aliases: ["Hockey"] },
      { name: "Tennis",          aliases: [] },
      { name: "Volleyball",      aliases: [] },
      { name: "Table Tennis",    aliases: ["Ping Pong"] },
      { name: "Basketball",      aliases: [] },
      { name: "Baseball",        aliases: [] },
      { name: "Rugby",           aliases: ["Rugby Union", "Rugby Football"] },
      { name: "Golf",            aliases: [] },
    ],
  },
  {
    id: "world-cup-finals",
    category: "Sports",
    prompt: "Countries with the most men's World Cup final appearances",
    items: [
      { name: "Germany",     aliases: ["West Germany", "Deutschland"] },
      { name: "Brazil",      aliases: ["Bresil"] },
      { name: "Argentina",   aliases: [] },
      { name: "Italy",       aliases: ["Italia"] },
      { name: "France",      aliases: [] },
      { name: "Netherlands", aliases: ["Holland"] },
      { name: "Uruguay",     aliases: [] },
      { name: "Czechoslovakia", aliases: [] },
      { name: "Hungary",     aliases: [] },
      { name: "England",     aliases: [] },
    ],
  },
];
